<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdConfirmation extends BaseSdConfirmation
{
  public function setHashAuto()
  {
    $hash = md5($this->getType().'-'.$this->getForeignId().'-'.$this->getAttributes());
    return $this->setHash($hash);
  }
}