<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdConfirmationTable extends Doctrine_Table
{
  public static function retrieveActivationByUserId($user_id)
  {
	$confirmation = Doctrine_Query::create()
				   ->select('c.*')
				   ->from('SdConfirmation c')
				   ->where('c.foreign_id = ?', $user_id)
				   ->andWhere("c.type = 'user_activation'")
				   ->fetchOne();	
	
	return $confirmation;
  }

  public static function getByHash($hash)
  {
	$q = Doctrine_Query::create()
				   		  ->select('c.*')
				    	  ->from('SdConfirmation c')
				   		  ->where('c.hash = ?', $hash);

	//var_dump($q->getSql()); die();
	
	$confirmation = $q->fetchOne();
	
	return $confirmation;
  }
}