<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdInvitation extends BaseSdInvitation 
{
	public function setHashAuto() {
		$hash = md5 ( $this->getInviterUserId () . '-' . $this->getInviteeUserId () . '-' . $this->getInviteeEmail () . '-' . $this->getProjectId () );
		return $this->setHash ( $hash );
	}
}