<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdInvitationTable extends Doctrine_Table 
{
	
	const SEND = 1;
	const ACCEPTED = 2;
	const REQUESTED = 0;
	
	public static function retrieveActivationByUserId ( $user_id ) 
	{
		$invitation = Doctrine_Query::create ()
						->select ( 'i.*' )
						->from ( 'SdInvitation i' )
						->where ( 'i.foreign_id = ?', $user_id )
						->andWhere ( "i.type = 'user_activation'" )
						->fetchOne ();
		
		return $invitation;
	}
	
	public static function getByHash ( $hash ) 
	{
		$q = Doctrine_Query::create ()
			->select ( 'i.*' )
			->from ( 'SdInvitation i' )
			->where ( 'i.hash = ?', $hash );
		
		//var_dump($q->getSql()); die();

		$invitation = $q->fetchOne ();
		return $invitation;
	}
	
	public static function isUserInvited ( $project_id, $invitee )
	{
		$q = Doctrine_Query::create ()
			->select ( '*' )
			->from ( 'SdInvitation i' )
			->where ( 'i.project_id = ?', $project_id )
			->andWhere ( 'i.status = 1' );
		
		if ( strpos( $invitee, '@' ) !== false )
			$q->andWhere ( "i.invitee_email = '$invitee'" );
		elseif( is_numeric( $invitee ) )
			$q->andWhere ( 'i.invitee_user_id = ?', $invitee );
		else 
			return false;
			
		$invitation = $q->fetchOne (); 
		return $invitation; 
	}
	
	public static function getInvitationByEmailAndProject ( $email, $projectId )
	{
		$invitation = Doctrine_Query::create ()
					->select ( 'i.*' )
					->from ( 'SdInvitation i' )
					->where ( "i.invitee_email = '$email'" )
					->andWhere ( "i.project_id = $projectId" )
					->andWhere ( "i.status = 1" )
					->fetchOne ();
		return $invitation;
	
	}
	
	public static function getInvitationByInviteeAndProject ( $inviteeId, $projectId )
	{
		$invitation = Doctrine_Query::create ()
					->select ( 'i.*' )
					->from ( 'SdInvitation i' )
					->where ( "i.invitee_user_id = $inviteeId" )
					->andWhere ( "i.project_id = $projectId" )
					->andWhere ( "i.status <= 1" )
					->fetchOne ();
		return $invitation;
	
	}
}