<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdProjectUserTable extends Doctrine_Table
{
  const OWNER = 1;
  const MEMBER = 2;
  const INVITED = 0;
  const REQUESTED = -1;

  public static function retrieveByUserIdAndProjectId($user_id, $project_id)
  {
	$project_user = Doctrine_Query::create()
				   ->select('pu.*')
				   ->from('SdProjectUser pu')
				   ->where('pu.user_id = ?', $user_id)
				   ->andWhere('pu.project_id = ?', $project_id)
				   ->fetchOne();	
	
	return $project_user;
  }

	//This function should be usable in many situations
	public static function getRecords($filters, $sort = array(), $options = array())
	{
//var_dump($sort);
//var_dump($filters);
		//setup the base query
		$q = Doctrine_Query::create()
			->from('SdProjectUser t');

		$selectString = 't.*';
		if(isset($options['joinUsers']))
		{
			$selectString .= ', u.*';
			$q->leftJoin('t.User SdUser u');
		}
		
		$q->select($selectString);

		//add filters
		if(is_array($filters))
		{
			$filterCount=0;
			foreach($filters as $fieldName => $fieldValue)
			{
				if($filterCount==0)
				{
					$whereFunc = 'where';
				}
				else
				{
					$whereFunc = 'andWhere';
				}
				if(trim($fieldValue)!='')
				{
					switch($fieldName)
					{
						default:
							$q->{$whereFunc}("t.".$fieldName." = ?", $fieldValue);
					}
					$filterCount++;
				}
			}
		}

		//add sort
		if(is_array($sort))
		{
			$orderString = '';
			$i=0;
			foreach($sort as $fieldName => $fieldValue)
			{
				if($fieldValue=='asc' || $fieldValue=='desc')
				{
					if($i>0)
						$orderString .= ', ';
					switch($fieldName)
					{
						default:
							$orderString .= 't.'.$fieldName.' '.$fieldValue;
					}
					$i++;
				}
			}
			if(trim($orderString)!='')
				$q->orderby($orderString);
		}

		//echo $q->getSql(); echo('<br>'); //die();
		
		$result = $q->execute();

		return $result;
	}
}