<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdProjectTable extends Doctrine_Table
{
  public static function getProjectsByUser($user)
  {
	$ssQuery = Doctrine_Query::create()
		->select('*')
		->from('SdProject p')
		->innerJoin('p.SdProjectUser pu WITH pu.user_id = '.$user->getId())
		->where('pu.role > 0');
	$projects = $ssQuery->execute(); 
	return $projects;
  }

  public static function getProjectUserArray($project_id, $projectUsers = NULL, $options = array())
  {
	$resultArray = array();
	if(isset($options['unassigned']) && $options['unassigned']===true)
	{
		$resultArray[''] = '-unassigned-';
	}
	
	if(is_null($projectUsers))
	{
		$project = Doctrine::getTable('SdProject')->find($project_id);
		$projectUsers = $project->getActiveProjectUsers();
	}
	foreach($projectUsers as $projectUser)
	{
		if(isset($options['objects']) && $options['objects']===true)
			$resultArray[$projectUser->User->getId()] = $projectUser->User;
		else
			$resultArray[$projectUser->User->getId()] = $projectUser->User->getFullName();
	}
	return $resultArray;
  }

  public static function getSprintArray($project_id)
  {
	$project = Doctrine::getTable('SdProject')->find($project_id);
	$sprints = $project->getActiveSprints();
	$resultArray = array('' => '-unassigned-');
	foreach($sprints as $sprint)
	{
		$resultArray[$sprint->getId()] = $sprint->getName();
	}
	return $resultArray;
  }
  
}