<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdQuestionTable extends Doctrine_Table
{
	//This function should be usable in many situations
	public static function getQuestions($filters, $sort = array(), $options = array())
	{
//var_dump($sort);
//var_dump($filters);
		//setup the base query
		$q = Doctrine_Query::create()
			->from('SdQuestion t');

		$q->select('t.*');
		
		if(isset($options['joinUsers']))
		{
			$selectString .= ', u.full_name';
			$q->leftJoin('t.User SdUser u');
		}
		
		if(isset($options['joinProjects']))
		{
			$selectString .= ', p.name';
			$q->leftJoin('t.Project SdProject p');
		}

		//add filters
		if(is_array($filters))
		{
			$filterCount=0;
			foreach($filters as $fieldName => $fieldValue)
			{
				if(trim((string)$fieldValue)!='')
				{
					if($filterCount==0)
					{
						$whereFunc = 'where';
						$whereInFunc = 'whereIn';
					}
					else
					{
						$whereFunc = 'andWhere';
						$whereInFunc = 'whereIn';
					}
					switch($fieldName)
					{
						case 'startDate':
							$q->{$whereFunc}("t.date >= ?", $fieldValue);
							break;
						case 'endDate':
							$q->{$whereFunc}("t.date <= ?", $fieldValue);
							break;
						case 'users':
							$q->{$whereInFunc}('t.user_id', $fieldValue);
							break;
						case 'projects':
							$q->{$whereInFunc}('t.project_id', $fieldValue);
							break;
						case 'hours':
							if($fieldValue=='>0')
							{
								$q->{$whereFunc}("t.".$fieldName." > 0");
							}
							else
								$q->{$whereFunc}("t.".$fieldName." = ?", $fieldValue);
							break;
						default:
							$q->{$whereFunc}("t.".$fieldName." = ?", $fieldValue);
					}
					$filterCount++;
				}
			}
		}

		//add sort
		if(is_array($sort))
		{
			$orderString = '';
			$i=0;
			foreach($sort as $fieldName => $fieldValue)
			{
				if($fieldValue=='asc' || $fieldValue=='desc')
				{
					if($i>0)
						$orderString .= ', ';
					switch($fieldName)
					{
						default:
							$orderString .= 't.'.$fieldName.' '.$fieldValue;
					}
					$i++;
				}
			}
			if(trim($orderString)!='')
				$q->orderby($orderString);
		}

		//echo $q->getSql(); echo('<br>'); //die();
		
		$result = $q->execute();

		return $result;
	}
}