<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdSprintTable extends Doctrine_Table
{
	public static $scrumDaysArr = array(0 => 'Sunday', 1 => 'Monday', 2 => 'Tuesday', 3 => 'Wednesday', 4 => 'Thursday', 5 => 'Friday', 6 => 'Saturday');
}