<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdTaskCommentTable extends Doctrine_Table
{
	public static function getTaskComments($taskId)
	{
		$taskComments = Doctrine_Query::create() 
						  ->select('u.full_name, tc.comment, tc.created_at, f.id')
						  ->from('SdTaskComment tc')
						  ->innerJoin('tc.User u')
							->leftJoin('u.ProfileImage f')
						  ->where('tc.task_id = ?', $taskId)
						  ->execute();
		
		return $taskComments;
	}
}