<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdTaskHoursTable extends Doctrine_Table
{
	//This function should be usable in many situations
	public static function getTaskHours($filters, $sort = array(), $options = array())
	{
//var_dump($sort);
//var_dump($filters);
		//setup the base query
		$q = Doctrine_Query::create()
			->from('SdTaskHours th');

		if(isset($options['joinTasks']))
		{
			$q->select('th.*, t.*')->innerJoin('th.Task SdTask t');
		}
		else
		$q->select('th.*');

		//add filters
		if(is_array($filters))
		{
			$filterCount=0;
			foreach($filters as $fieldName => $fieldValue)
			{
				if($filterCount==0)
				{
					$whereFunc = 'where';
				}
				else
				{
					$whereFunc = 'andWhere';
				}
				if(trim($fieldValue)!='')
				{
					switch($fieldName)
					{
						case 'startDate':
							$q->{$whereFunc}("th.date >= ?", $fieldValue);
							break;
						case 'endDate':
							$q->{$whereFunc}("th.date <= ?", $fieldValue);
							break;
						default:
							$q->{$whereFunc}("th.".$fieldName." = ?", $fieldValue);
					}
					$filterCount++;
				}
			}
		}

		//add sort
		if(is_array($sort))
		{
			$orderString = '';
			$i=0;
			foreach($sort as $fieldName => $fieldValue)
			{
				if($fieldValue=='asc' || $fieldValue=='desc')
				{
					if($i>0)
						$orderString .= ', ';
					switch($fieldName)
					{
						default:
							$orderString .= 'th.'.$fieldName.' '.$fieldValue;
					}
					$i++;
				}
			}
			if(trim($orderString)!='')
				$q->orderby($orderString);
		}

		//echo $q->getSql(); echo('<br>'); //die();
		
		$taskHours = $q->execute();

		return $taskHours;
	}
}