<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SdUserTable extends Doctrine_Table {
	public static function retrieveByUsername($username) {
		$user = Doctrine::getTable ( 'SdUser' )->findOneByUsername ( $username );
		return $user;
	}
	
	public static function retrieveByEmail($email) {
		$user = Doctrine::getTable ( 'SdUser' )->findOneByEmail ( $email );
		return $user;
	}
	
	public static function getTimeZoneArray() {
		$zones = timezone_identifiers_list ();
		foreach ( $zones as $k => $v ) {
			$resultArray [$v] = $v;
		}
		return $resultArray;
	}
	
	public function searchUsers($text) {
		
		$users = Doctrine_Query::create ()
			->from ( 'SdUser u' )
			->where ( "u.full_name like '%$text%'")
			->orWhere ( "u.username like '%$text%'" )
			->execute ();
		
		return $users;
	}
	
	public static function isUserEmail ( $email )
	{
		$user = Doctrine_Query::create()
				->select('u.*')
				->from('SdUser u')
				->where("u.email = '$email'")
				->fetchOne();
		
		return $user;
	}

}